#include "colisao.h"
#include "fundos.h"

enum Terreno {
    LIVRE,
    OBSTACULO,
    GRAMA
};

/*
inicializar de acordo com fundos.h

const unsigned short rota1_fundo[576][320];
const unsigned short casa1_fundo[128][128];
const unsigned short casa2_fundo[128][128];
const unsigned short casa_rival_fundo[128][128];
const unsigned short lab_fundo[192][160];
const unsigned short cidade_fundo[288][320];

em que cada mapa de colisão tem dimensões [altura/16][largura/16]
*/

enum Terreno rota1_colisao[36][20] = {
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, LIVRE, LIVRE, GRAMA, GRAMA, GRAMA, GRAMA, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, GRAMA, GRAMA, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
};

enum Terreno casa1_colisao[8][8] = {
    {OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO},
    {OBSTACULO, OBSTACULO, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE},
    {LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
};

enum Terreno casa2_colisao[8][8] = {
    {OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO},
    {OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
};

enum Terreno casa_rival_colisao[8][8] = {
    {OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO},
    {OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE},
    {LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
};

enum Terreno lab_colisao[12][10] = {
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE},
    {LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE}
};

enum Terreno cidade_colisao[18][20] = {
    {LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, GRAMA, GRAMA, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, LIVRE},
    {OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, GRAMA, GRAMA, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, LIVRE, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, LIVRE, OBSTACULO},
    {OBSTACULO, OBSTACULO, LIVRE, LIVRE, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO, OBSTACULO},
};
